// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DannyKeyboard.Domain.Entities;

public partial class Cart
{
    public int CartId { get; set; }

    public string CustomerId { get; set; }

    public int TotalItems { get; set; }

    public string PromotionCode { get; set; }

    public decimal SubTotal { get; set; }

    public decimal? ShippingPrice { get; set; }

    public decimal TotalPrice { get; set; }

    public int Status { get; set; }
}