// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DannyKeyboard.Domain.Entities;

public partial class ChatConversation
{
    public int ConversationId { get; set; }

    public string CustomerId { get; set; }

    public string StaffId { get; set; }

    public string OrderId { get; set; }

    public DateTime CreatedAt { get; set; }
}