// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DannyKeyboard.Domain.Entities;

public partial class Keyboard
{
    public string KeyboardId { get; set; }

    public string Images { get; set; }

    public string CaseId { get; set; }

    public string SwitchId { get; set; }

    public string StabilizerId { get; set; }

    public string KeycapId { get; set; }

    public string Pcbid { get; set; }

    public string PlateId { get; set; }
}