// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DannyKeyboard.Domain.Entities;

public partial class Notification
{
    public int NotificationId { get; set; }

    public string Title { get; set; }

    public string Message { get; set; }

    public string SenderId { get; set; }

    public string ReceiverId { get; set; }

    public string Type { get; set; }

    public DateTime CreateAt { get; set; }

    public bool IsRead { get; set; }
}