// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DannyKeyboard.Domain.Entities;

public partial class Pcb
{
    public string Pcbid { get; set; }

    public string Images { get; set; }

    public string CircuitType { get; set; }

    public string Led { get; set; }

    public bool IsHotSwapping { get; set; }
}