// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DannyKeyboard.Domain.Entities;

public partial class Plate
{
    public string PlateId { get; set; }

    public string Images { get; set; }

    public string PlateType { get; set; }

    public string TypeDescription { get; set; }

    public bool IsScrewing { get; set; }
    public virtual ICollection<Keyboard> Keyboards { get; set; } = new List<Keyboard>();

    public virtual Product PlateNavigation { get; set; }
}