// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DannyKeyboard.Domain.Entities;

public partial class Product
{
    public string ProductId { get; set; }

    public string ProductName { get; set; }

    public string ProductDescription { get; set; }

    public int Quantity { get; set; }

    public decimal? UnitPrice { get; set; }

    public int BrandId { get; set; }

    public int CategoryId { get; set; }

    public int Status { get; set; }
}