// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DannyKeyboard.Domain.Entities;

public partial class Rating
{
    public int RatingId { get; set; }

    public string OrderId { get; set; }

    public string CustomerId { get; set; }

    public double Score { get; set; }

    public string Comment { get; set; }

    public DateTime CreatedDate { get; set; }
}