// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DannyKeyboard.Domain.Entities;

public partial class Stabilizer
{
    public string StabilizerId { get; set; }

    public string Images { get; set; }

    public string Size { get; set; }

    public string Material { get; set; }
}