// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DannyKeyboard.Domain.Entities;

public partial class Staff
{
    public string StaffId { get; set; }

    public string FullName { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public DateOnly Dob { get; set; }
}