// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DannyKeyboard.Domain.Entities;

public partial class StaffSchedule
{
    public int ScheduleId { get; set; }

    public string StaffId { get; set; }

    public int ShiftId { get; set; }

    public string Tasks { get; set; }

    public DateOnly WorkDate { get; set; }

    public bool IsPresent { get; set; }

    public string Note { get; set; }
}