// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DannyKeyboard.Domain.Entities;

public partial class TransactionHistory
{
    public int TransactionHistoryId { get; set; }

    public string OrderId { get; set; }

    public string CustomerId { get; set; }

    public decimal TotalPrice { get; set; }

    public int PaymentMethodId { get; set; }

    public DateOnly PaymentDate { get; set; }
}