// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DannyKeyboard.Domain.Entities9999;

public partial class AboutU
{
    public int AboutUsId { get; set; }

    public string Detail { get; set; }

    public bool IsActive { get; set; }
}