// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DannyKeyboard.Domain.Entities9999;

public partial class ChatMessage
{
    public int MessageId { get; set; }

    public int? ConversationId { get; set; }

    public string SenderId { get; set; }

    public int SenderRoleId { get; set; }

    public string MessageText { get; set; }

    public DateTime SendAt { get; set; }

    public virtual ChatConversation Conversation { get; set; }

    public virtual User Sender { get; set; }
}