// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DannyKeyboard.Domain.Entities9999;

public partial class Keyboard
{
    public string KeyboardId { get; set; }

    public string Images { get; set; }

    public string CaseId { get; set; }

    public string SwitchId { get; set; }

    public string StabilizerId { get; set; }

    public string KeycapId { get; set; }

    public string Pcbid { get; set; }

    public string PlateId { get; set; }

    public virtual Case Case { get; set; }

    public virtual Product KeyboardNavigation { get; set; }

    public virtual Keycap Keycap { get; set; }

    public virtual Pcb Pcb { get; set; }

    public virtual Plate Plate { get; set; }

    public virtual Stabilizer Stabilizer { get; set; }

    public virtual Switch Switch { get; set; }
}