// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DannyKeyboard.Domain.Entities9999;

public partial class Order
{
    public string OrderId { get; set; }

    public int CartId { get; set; }

    public string CustomerId { get; set; }

    public decimal TotalPrice { get; set; }

    public DateTime CreatedAt { get; set; }

    public int PaymentMethodId { get; set; }

    public DateOnly EstDeliveryDate { get; set; }

    public DateOnly? RealDeliveryDate { get; set; }

    public string Note { get; set; }

    public int Status { get; set; }

    public virtual Cart Cart { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<Rating> Ratings { get; set; } = new List<Rating>();

    public virtual ICollection<TransactionHistory> TransactionHistories { get; set; } = new List<TransactionHistory>();
}