// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DannyKeyboard.Domain.Entities9999;

public partial class Policy
{
    public int PolicyId { get; set; }

    public string PolicyName { get; set; }

    public bool IsActive { get; set; }
}