// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DannyKeyboard.Domain.Entities9999;

public partial class Product
{
    public string ProductId { get; set; }

    public string ProductName { get; set; }

    public string ProductDescription { get; set; }

    public int Quantity { get; set; }

    public decimal? UnitPrice { get; set; }

    public int BrandId { get; set; }

    public int CategoryId { get; set; }

    public int Status { get; set; }

    public virtual Brand Brand { get; set; }

    public virtual ICollection<CartDetail> CartDetails { get; set; } = new List<CartDetail>();

    public virtual Case Case { get; set; }

    public virtual Category Category { get; set; }

    public virtual Keyboard Keyboard { get; set; }

    public virtual Keycap Keycap { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual Pcb Pcb { get; set; }

    public virtual Plate Plate { get; set; }

    public virtual Stabilizer Stabilizer { get; set; }

    public virtual Switch Switch { get; set; }
}