// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DannyKeyboard.Domain.Entities9999;

public partial class Promotion
{
    public int PromotionId { get; set; }

    public string Code { get; set; }

    public string PromotionName { get; set; }

    public string Description { get; set; }

    public int DiscountType { get; set; }

    public int Value { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public int? MaxUse { get; set; }

    public bool IsActive { get; set; }
}