// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DannyKeyboard.Domain.Entities9999;

public partial class Stabilizer
{
    public string StabilizerId { get; set; }

    public string Images { get; set; }

    public string Size { get; set; }

    public string Material { get; set; }

    public virtual ICollection<Keyboard> Keyboards { get; set; } = new List<Keyboard>();

    public virtual Product StabilizerNavigation { get; set; }
}