// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DannyKeyboard.Domain.Entities9999;

public partial class Staff
{
    public string StaffId { get; set; }

    public string FullName { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public DateOnly Dob { get; set; }

    public virtual ICollection<ChatConversation> ChatConversations { get; set; } = new List<ChatConversation>();

    public virtual User StaffNavigation { get; set; }

    public virtual ICollection<StaffSchedule> StaffSchedules { get; set; } = new List<StaffSchedule>();
}