// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DannyKeyboard.Domain.Entities9999;

public partial class Switch
{
    public string SwitchId { get; set; }

    public string Images { get; set; }

    public string Color { get; set; }

    public string SwitchType { get; set; }

    public string ActuationForce { get; set; }

    public string ActuationPoint { get; set; }

    public string TravelDistance { get; set; }

    public string Material { get; set; }

    public bool IsLedThrough { get; set; }

    public virtual ICollection<Keyboard> Keyboards { get; set; } = new List<Keyboard>();

    public virtual Product SwitchNavigation { get; set; }
}