// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DannyKeyboard.Domain.Entities9999;

public partial class User
{
    public string UserId { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public DateOnly CreatedDate { get; set; }

    public int RoleId { get; set; }

    public string ResetCode { get; set; }

    public string RefreshToken { get; set; }

    public DateTime? RefreshTokenExpiryTime { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<ChatMessage> ChatMessages { get; set; } = new List<ChatMessage>();

    public virtual Customer Customer { get; set; }

    public virtual Role Role { get; set; }

    public virtual Staff Staff { get; set; }
}